### ISSUE TITLE
mp_sort, random.shuffle() returns undefined but random.choice() works

### ISSUE THREAD

**Issue by otakuprof** [Data-Driven-World/d2w_mini_projects#14]
This is done locally on MacBook Pro with Google chrome. 
![Screen Shot 2021-09-10 at 11 45 04 AM](https://user-images.githubusercontent.com/31842385/132796472-ee199f09-f3fd-40f7-bfd8-421f7c1b3082.png)

**Comment by kurniawano** [comment]
@otakuprof , `random.shuffle()` shuffles the items **in-place**. So it returns nothing. Try:
```
random.shuffle(a)
console.log(a)
```

**Comment by otakuprof** [comment]
Thanks, my bad, forgot to check if it is done in-place.
