### ISSUE TITLE
Repo to clone from

### ISSUE THREAD

**Issue by iangohy** [Data-Driven-World/d2w_mini_projects#18]
Hi prof,

Noticed that for all the mini projects, the first instruction is always to clone the repo using 
```
$ git clone https://github.com/kurniawano/d2w_mini_projects.git
```
However, it seems that the repo on your account is not as updated as the one at `https://github.com/Data-Driven-World/d2w_mini_projects.git`.

Should the repo to clone be the one in `Data-Driven-World` instead?

**Comment by kurniawano** [comment]
Hi @iangohy , yes, I would like to rewrite the handout using public template, so they should click Use template and clone from their own private template, or the public repo. I will do this after the term end. I will keep the issue open. Thanks.
